apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-streamlit-ui-dev
  namespace: argocd
spec:
  project: default

  sources:
    # Source 1: Repo A (Helm chart)
    - repoURL: https://github.com/Venkat8538/mlops-streamlit-ui.git
      targetRevision: main
      path: helm/mlops-streamlit-ui
      helm:
        valueFiles:
          - $values/envs/dev/mlops-streamlit-ui-values.yaml

    # Source 2: Repo B (values)
    - repoURL: https://github.com/Venkat8538/platform-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: streamlit

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
