apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-streamlit-ui-prod
  namespace: argocd
spec:
  project: default

  sources:
    - repoURL: https://github.com/Venkat8538/mlops-streamlit-ui.git
      targetRevision: main
      path: helm/mlops-streamlit-ui
      helm:
        valueFiles:
          - $values/envs/prod/mlops-streamlit-ui-values.yaml

    - repoURL: https://github.com/Venkat8538/platform-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: streamlit

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
